# -*- coding: utf-8 -*-
"""HTML_Quick_Styler.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sTvPq9Rc9BKl3CiSRQzEW4mVs5c7huUO
"""

!pip install gradio transformers torch

import gradio as gr
from transformers import pipeline

generator = pipeline(
    "text-generation",
    model="ibm-granite/granite-3.3-2b-instruct"
)

def generate_html(description):

    prompt = f"""
    Create a simple HTML webpage with CSS.

    Website description:
    {description}

    Generate clean HTML with internal CSS styling.
    """

    result = generator(prompt, max_new_tokens=400)

    return result[0]["generated_text"]

interface = gr.Interface(
    fn=generate_html,
    inputs=gr.Textbox(lines=5, label="Describe your website"),
    outputs="textbox",
    title="HTML Quick Styler",
    description="AI Powered HTML Page Generator"
)

import gradio as gr
from transformers import pipeline

generator = pipeline(
    "text-generation",
    model="ibm-granite/granite-3.3-2b-instruct"
)

def generate_html(description):

    prompt = f"""
    Create a simple HTML webpage with CSS.

    Website description:
    {description}

    Generate clean HTML with internal CSS styling.
    """

    result = generator(prompt, max_new_tokens=400)

    return result[0]["generated_text"]

interface = gr.Interface(
    fn=generate_html,
    inputs=gr.Textbox(lines=5, label="Describe your website"),
    outputs="textbox",
    title="HTML Quick Styler",
    description="AI Powered HTML Page Generator"
)
interface.launch()

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Freelance Designer Portfolio</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }

       .hero {
            background-color: #282c34;
            color: white;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            padding: 2rem;
        }

       .hero h1 {
            font-size: 2.5rem;
            margin: 0;
        }

       .hero p {
            font-size: 1.25rem;
            margin: 1rem 0;
        }

       .call-to-action {
            background-color: #3498db;
            color: white;
            padding: 1rem;
            display: inline-block;
            border-radius: 5px;
            margin-top: 2rem;
        }

       .portfolio-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 2rem;
            padding: 2rem;
        }

       .portfolio-item {
            background-color: #fff;
            padding: 1rem;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            display: flex;
            flex-direction: column;
            align-items: center;
        }

       .portfolio

import gradio as gr

def generate_html(description):

    html_code = f"""
<!DOCTYPE html>
<html>
<head>
<title>Generated Website</title>
<style>
body {{
font-family: Arial;
background:#f4f4f4;
padding:40px;
}}

.container {{
background:white;
padding:20px;
border-radius:10px;
}}

</style>
</head>

<body>

<div class="container">
<h1>AI Generated Page</h1>
<p>{description}</p>
</div>

</body>
</html>
"""

    return html_code


interface = gr.Interface(
    fn=generate_html,
    inputs="textbox",
    outputs="textbox",
    title="HTML Quick Styler"
)

interface.launch()

<!DOCTYPE html>
<html>
<head>
<title>Generated Website</title>
<style>
body {
font-family: Arial;
background:#f4f4f4;
padding:40px;
}

.container {
background:white;
padding:20px;
border-radius:10px;
}

</style>
</head>

<body>

<div class="container">
<h1>AI Generated Page</h1>
<p>A freelance designer wants to create a professional portfolio website quickly and efficiently. The system first detects the project requirements and analyzes the designer’s style and design preferences. Based on this understanding, it generates a complete website structure that includes a visually appealing hero section with a welcoming message and a strong call-to-action to engage visitors immediately. It also builds a responsive portfolio gallery arranged in a clean grid layout to showcase projects effectively across devices. An about section is created to present the designer’s professional bio in a compelling manner, helping visitors understand their background and expertise. To strengthen credibility, the system includes a testimonials section featuring client feedback. A contact form with proper input validation ensures smooth communication while preventing errors, and finally, a professional footer is added with social media links and essential information to complete the polished look of the website.
</p>
</div>

</body>
</html>