# -*- coding: utf-8 -*-
"""HTML_Quick_Styler.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sTvPq9Rc9BKl3CiSRQzEW4mVs5c7huUO
"""

!pip install gradio transformers torch

import gradio as gr
from transformers import pipeline

generator = pipeline(
    "text-generation",
    model="ibm-granite/granite-3.3-2b-instruct"
)

def generate_html(description):

    prompt = f"""
    Create a simple HTML webpage with CSS.

    Website description:
    {description}

    Generate clean HTML with internal CSS styling.
    """

    result = generator(prompt, max_new_tokens=400)

    return result[0]["generated_text"]

interface = gr.Interface(
    fn=generate_html,
    inputs="text",
    outputs="text",
    title="HTML Quick Styler",
    description="AI Powered HTML Page Generator"
)

interface.launch()