# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WoMYFOUSgmbrbPPjLwO2a9-h5bQWLuqV
"""

!pip install transformers accelerate torch gradio --quiet

import torch
print("GPU Available:", torch.cuda.is_available())
print("Torch Version:", torch.__version__)

# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
model = AutoModelForCausalLM.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
messages = [
    {"role": "user", "content": "Who are you?"},
]
inputs = tokenizer.apply_chat_template(
	messages,
	add_generation_prompt=True,
	tokenize=True,
	return_dict=True,
	return_tensors="pt",
).to(model.device)

outputs = model.generate(**inputs, max_new_tokens=40)
print(tokenizer.decode(outputs[0][inputs["input_ids"].shape[-1]:]))

# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("text-generation", model="ibm-granite/granite-3.3-2b-instruct")
messages = [
    {"role": "user", "content": "Who are you?"},
]
pipe(messages)

from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline

model_name = "ibm-granite/granite-3.3-2b-instruct"

# Load tokenizer and model
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name, device_map="auto")

# Set up a text generation pipeline
granite_pipeline = pipeline("text-generation", model=model, tokenizer=tokenizer)

prompt = "Explain in simple words what machine learning is."
result = granite_pipeline(prompt, max_new_tokens=100)
print(result[0]['generated_text'])

result = granite_pipeline(prompt, max_new_tokens=150, temperature=0.7, top_p=0.9)
print(result[0]['generated_text'])

!pip install gradio --quiet

import gradio as gr

def granite_generate(text):
    output = granite_pipeline(text, max_new_tokens=100)
    return output[0]['generated_text']

# Create Gradio Interface
iface = gr.Interface(fn=granite_generate, inputs="text", outputs="text",
                     title="Granite 3.3 2B Instruct Demo",
                     description="Enter text and get generated output from Granite model.")
iface.launch(share=True)  # 'share=True' gives a public link

class ColorPaletteGenerator:
    def __init__(self):
        # Define 8 color palette schemes
        self.palettes = {
            "Sunset": ["#FF5E5B", "#D8D8D8", "#FFED66", "#3B2F2F", "#FF7F50"],
            "Ocean": ["#0077B6", "#00B4D8", "#90E0EF", "#CAF0F8", "#03045E"],
            "Forest": ["#2D6A4F", "#95D5B2", "#52B788", "#1B4332", "#D8F3DC"],
            "Pastel": ["#F8B195", "#F67280", "#C06C84", "#6C5B7B", "#355C7D"],
            "Monochrome": ["#000000", "#333333", "#666666", "#999999", "#FFFFFF"],
            "Candy": ["#FF6B6B", "#FFD93D", "#6BCB77", "#4D96FF", "#FF9CEE"],
            "Earth": ["#A0522D", "#CD853F", "#DEB887", "#F5F5DC", "#8B4513"],
            "Vibrant": ["#FF0000", "#FF7F00", "#FFFF00", "#00FF00", "#0000FF"]
        }

    def get_palette(self, name):
        # Return palette if exists, else default
        return self.palettes.get(name, self.palettes["Monochrome"])

    def validate_color(self, color_code):
        # Simple HEX color validation
        import re
        pattern = r"^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$"
        return bool(re.match(pattern, color_code))

class HTMLPageBuilder:
    def __init__(self, title="My Website", palette=None):
        self.title = title
        self.palette = palette if palette else ["#000000", "#FFFFFF"]
        self.sections = []

    def add_section(self, section_html):
        self.sections.append(section_html)

    def generate_meta_tags(self, description="This is a website", keywords="website, html, python"):
        return f"""
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="{description}">
        <meta name="keywords" content="{keywords}">
        <title>{self.title}</title>
        """

    def build_page(self):
        body_content = "\n".join(self.sections)
        return f"""
        <!DOCTYPE html>
        <html lang="en">
        <head>
            {self.generate_meta_tags()}
        </head>
        <body style="background-color:{self.palette[1]}; color:{self.palette[0]};">
            {body_content}
        </body>
        </html>
        """

class CSSGenerator:
    def __init__(self):
        self.styles = []

    def add_base_style(self, selector, rules):
        css = f"{selector} {{\n"
        for prop, val in rules.items():
            css += f"  {prop}: {val};\n"
        css += "}\n"
        self.styles.append(css)

    def add_media_query(self, max_width, rules):
        css = f"@media (max-width: {max_width}px) {{\n"
        for selector, props in rules.items():
            css += f"  {selector} {{\n"
            for prop, val in props.items():
                css += f"    {prop}: {val};\n"
            css += "  }\n"
        css += "}\n"
        self.styles.append(css)

    def add_animation(self, name, keyframes):
        css = f"@keyframes {name} {{\n"
        for percent, props in keyframes.items():
            css += f"  {percent}% {{\n"
            for prop, val in props.items():
                css += f"    {prop}: {val};\n"
            css += "  }\n"
        css += "}\n"
        self.styles.append(css)

    def build_css(self):
        return "\n".join(self.styles)

# Hero Section
def hero_section(title="Welcome", subtitle="This is my website", btn_text="Get Started"):
    return f"""
    <section class="hero">
        <h1>{title}</h1>
        <p>{subtitle}</p>
        <button>{btn_text}</button>
    </section>
    """

# Features Grid
def features_grid(features):
    html = '<section class="features"><div class="grid">'
    for f in features:
        html += f'<div class="feature-card"><h3>{f["title"]}</h3><p>{f["desc"]}</p></div>'
    html += '</div></section>'
    return html

# Portfolio Gallery
def portfolio_gallery(items):
    html = '<section class="portfolio"><div class="gallery">'
    for item in items:
        html += f'<div class="portfolio-item"><img src="{item["img"]}" alt="{item["title"]}"><p>{item["title"]}</p></div>'
    html += '</div></section>'
    return html

# Contact Form
def contact_form():
    return """
    <section class="contact">
        <form>
            <input type="text" name="name" placeholder="Your Name" required>
            <input type="email" name="email" placeholder="Your Email" required>
            <textarea name="message" placeholder="Your Message"></textarea>
            <button type="submit">Send</button>
        </form>
    </section>
    """

# Pricing Template
def pricing_table(plans):
    html = '<section class="pricing"><div class="plans">'
    for p in plans:
        html += f'<div class="plan"><h3>{p["name"]}</h3><p>{p["price"]}</p><p>{p["features"]}</p></div>'
    html += '</div></section>'
    return html

import gradio as gr
from datetime import datetime

# Assume these are already defined from Phase 2
# from phase2_core import HTMLPageBuilder, CSSGenerator, ColorPaletteGenerator, hero_section, features_grid, portfolio_gallery, contact_form, pricing_table

def generate_html(template_choice, palette_name, title, subtitle):
    # Initialize ColorPaletteGenerator
    color_gen = ColorPaletteGenerator()
    palette = color_gen.get_palette(palette_name)

    # Initialize HTMLPageBuilder
    page = HTMLPageBuilder(title=title, palette=palette)

    # Add template section based on user choice
    if template_choice == "Hero":
        page.add_section(hero_section(title, subtitle))
    elif template_choice == "Features":
        features = [{"title":"Fast","desc":"Optimized performance"},
                    {"title":"Secure","desc":"Secure by design"}]
        page.add_section(features_grid(features))
    elif template_choice == "Portfolio":
        items = [{"title":"Project 1","img":"https://via.placeholder.com/150"},
                 {"title":"Project 2","img":"https://via.placeholder.com/150"}]
        page.add_section(portfolio_gallery(items))
    elif template_choice == "Contact":
        page.add_section(contact_form())
    elif template_choice == "Pricing":
        plans = [{"name":"Basic","price":"$10","features":"Feature A, Feature B"},
                 {"name":"Pro","price":"$20","features":"Feature A, B, C"}]
        page.add_section(pricing_table(plans))

    # Build HTML
    html_code = page.build_page()

    return html_code

def preview_html(template_choice, palette_name, title, subtitle):
    html_code = generate_html(template_choice, palette_name, title, subtitle)
    return html_code

with gr.Blocks() as demo:
    gr.Markdown("## HTML Page Generator & Preview")

    with gr.Tabs():
        with gr.Tab("Generate HTML"):
            template_choice = gr.Dropdown(["Hero","Features","Portfolio","Contact","Pricing"], label="Choose Template")
            palette_name = gr.Dropdown(["Sunset","Ocean","Forest","Pastel","Monochrome","Candy","Earth","Vibrant"], label="Choose Color Palette")
            title = gr.Textbox(label="Page Title", value="My Website")
            subtitle = gr.Textbox(label="Subtitle", value="Welcome to my website")
            html_output = gr.Textbox(label="Generated HTML", lines=20)
            generate_btn = gr.Button("Generate HTML")

            generate_btn.click(generate_html, inputs=[template_choice, palette_name, title, subtitle], outputs=html_output)

        with gr.Tab("Preview"):
            preview_output = gr.HTML(label="Live Preview")
            preview_btn = gr.Button("Show Preview")
            preview_btn.click(preview_html, inputs=[template_choice, palette_name, title, subtitle], outputs=preview_output)

demo.launch(share=True)

import torch
import gradio as gr
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
from datetime import datetime

# Phase 2 classes and functions
# ColorPaletteGenerator, HTMLPageBuilder, CSSGenerator
# Templates: hero_section, features_grid, portfolio_gallery, contact_form, pricing_table

# Correct Hugging Face model path
model_name = "ibm-granite/granite-3.3-2b-instruct"

# Load tokenizer and model with GPU
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name, device_map="auto")

# Create pipeline
granite_pipeline = pipeline("text-generation", model=model, tokenizer=tokenizer)

test_prompt = "Explain responsive web design in simple words."
print(granite_pipeline(test_prompt, max_new_tokens=100)[0]['generated_text'])

def generate_html_with_ai(template_choice, palette_name, title, subtitle, ai_prompt):
    # Step 1: Get color palette
    color_gen = ColorPaletteGenerator()
    palette = color_gen.get_palette(palette_name)

    # Step 2: Generate HTML template
    page = HTMLPageBuilder(title=title, palette=palette)
    if template_choice == "Hero":
        page.add_section(hero_section(title, subtitle))
    elif template_choice == "Features":
        features = [{"title":"Fast","desc":"Optimized performance"},
                    {"title":"Secure","desc":"Secure by design"}]
        page.add_section(features_grid(features))
    elif template_choice == "Portfolio":
        items = [{"title":"Project 1","img":"https://via.placeholder.com/150"},
                 {"title":"Project 2","img":"https://via.placeholder.com/150"}]
        page.add_section(portfolio_gallery(items))
    elif template_choice == "Contact":
        page.add_section(contact_form())
    elif template_choice == "Pricing":
        plans = [{"name":"Basic","price":"$10","features":"Feature A, Feature B"},
                 {"name":"Pro","price":"$20","features":"Feature A, B, C"}]
        page.add_section(pricing_table(plans))

    # Step 3: Generate AI content if prompt given
    if ai_prompt.strip() != "":
        ai_text = granite_pipeline(ai_prompt, max_new_tokens=100)[0]['generated_text']
        page.add_section(f"<section><p>{ai_text}</p></section>")

    # Step 4: Build final HTML
    html_code = page.build_page()
    return html_code

def preview_html(template_choice, palette_name, title, subtitle, ai_prompt):
    html_code = generate_html_with_ai(template_choice, palette_name, title, subtitle, ai_prompt)
    return html_code

with gr.Blocks() as demo:
    gr.Markdown("## HTML Page Generator with Granite AI Integration")

    with gr.Tabs():
        with gr.Tab("Generate HTML"):
            template_choice = gr.Dropdown(["Hero","Features","Portfolio","Contact","Pricing"], label="Choose Template")
            palette_name = gr.Dropdown(["Sunset","Ocean","Forest","Pastel","Monochrome","Candy","Earth","Vibrant"], label="Choose Color Palette")
            title = gr.Textbox(label="Page Title", value="My Website")
            subtitle = gr.Textbox(label="Subtitle", value="Welcome to my website")
            ai_prompt = gr.Textbox(label="Optional AI Content Prompt", placeholder="Enter something for AI to generate...")
            html_output = gr.Textbox(label="Generated HTML", lines=20)
            generate_btn = gr.Button("Generate HTML")

            generate_btn.click(generate_html_with_ai,
                               inputs=[template_choice, palette_name, title, subtitle, ai_prompt],
                               outputs=html_output)

        with gr.Tab("Preview"):
            preview_output = gr.HTML(label="Live Preview")
            preview_btn = gr.Button("Show Preview")
            preview_btn.click(preview_html,
                              inputs=[template_choice, palette_name, title, subtitle, ai_prompt],
                              outputs=preview_output)

demo.launch(share=True)

demo.launch(share=True, server_name="0.0.0.0", server_port=7860)

def add_portfolio_css(css_gen):
    css_gen.add_base_style(".portfolio", {
        "padding": "20px",
        "text-align": "center"
    })
    css_gen.add_base_style(".gallery", {
        "display": "flex",
        "flex-wrap": "wrap",
        "gap": "20px",
        "justify-content": "center"
    })
    css_gen.add_base_style(".portfolio-item", {
        "width": "200px",
        "border": "1px solid #ddd",
        "border-radius": "8px",
        "padding": "10px",
        "box-shadow": "0 2px 5px rgba(0,0,0,0.1)"
    })
    css_gen.add_base_style(".portfolio-item img", {
        "width": "100%",
        "height": "auto",
        "border-radius": "5px"
    })

def portfolio_gallery(items):
    html = '<section class="portfolio"><h2>Portfolio</h2><div class="gallery">'
    for item in items:
        html += f'''
        <div class="portfolio-item">
            <img src="{item["img"]}" alt="{item["title"]}">
            <p>{item["title"]}</p>
        </div>
        '''
    html += '</div></section>'
    return html

css_gen = CSSGenerator()
add_portfolio_css(css_gen)
css_code = css_gen.build_css()

# Define items for the portfolio gallery
items = [
    {"title":"Project Alpha","img":"https://via.placeholder.com/150/FF0000/FFFFFF?text=Project1"},
    {"title":"Project Beta","img":"https://via.placeholder.com/150/00FF00/000000?text=Project2"},
    {"title":"Project Gamma","img":"https://via.placeholder.com/150/0000FF/FFFFFF?text=Project3"}
]

# Include in HTML <head>
html_code = f"""
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Portfolio Page</title>
<style>
{css_code}
</style>
</head>
<body>
{portfolio_gallery(items)}
</body>
</html>
"""

css_gen.add_base_style(".portfolio-item:hover", {
    "transform": "scale(1.05)",
    "transition": "0.3s"
})

# Step 1: Generate CSS
css_gen = CSSGenerator()

# Add portfolio CSS
def add_portfolio_css(css_gen):
    css_gen.add_base_style(".portfolio", {"padding":"20px","text-align":"center"})
    css_gen.add_base_style(".gallery", {"display":"flex","flex-wrap":"wrap","gap":"20px","justify-content":"center"})
    css_gen.add_base_style(".portfolio-item", {"width":"200px","border":"1px solid #ddd","border-radius":"8px","padding":"10px","box-shadow":"0 2px 5px rgba(0,0,0,0.1)"})
    css_gen.add_base_style(".portfolio-item img", {"width":"100%","height":"auto","border-radius":"5px"})
    css_gen.add_base_style(".portfolio-item:hover", {"transform":"scale(1.05)","transition":"0.3s"})

add_portfolio_css(css_gen)
css_code = css_gen.build_css()

# Step 2: Build HTML with embedded CSS
html_code = f"""
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Portfolio Page</title>
<style>
{css_code}
</style>
</head>
<body>
{portfolio_gallery(items)}
</body>
</html>
"""

with open("style.css", "w") as f:
    f.write(css_code)

html_code = f"""
<link rel="stylesheet" href="style.css">
<body>
{portfolio_gallery(items)}
</body>
"""

def generate_html_with_css(template_choice, palette_name, title, subtitle, ai_prompt):
    # Color palette
    color_gen = ColorPaletteGenerator()
    palette = color_gen.get_palette(palette_name)

    # HTML page
    page = HTMLPageBuilder(title=title, palette=palette)
    if template_choice == "Portfolio":
        items = [{"title":"Project 1","img":"https://via.placeholder.com/150"},
                 {"title":"Project 2","img":"https://via.placeholder.com/150"}]
        page.add_section(portfolio_gallery(items))

    # AI content
    if ai_prompt.strip() != "":
        ai_text = granite_pipeline(ai_prompt, max_new_tokens=100)[0]['generated_text']
        page.add_section(f"<section><p>{ai_text}</p></section>")

    # Generate CSS
    css_gen = CSSGenerator()
    add_portfolio_css(css_gen)
    css_code = css_gen.build_css()

    # Embed CSS inside HTML
    html_code = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
    {css_code}
    </style>
    </head>
    <body>
    {page.build_page()}
    </body>
    </html>
    """
    return html_code

import gradio as gr

with gr.Blocks() as demo:
    with gr.Tabs():
        with gr.Tab("Generate HTML"):
            template_choice = gr.Dropdown(["Hero","Features","Portfolio","Contact","Pricing"], label="Choose Template")
            palette_name = gr.Dropdown(["Sunset","Ocean","Forest","Pastel","Monochrome","Candy","Earth","Vibrant"], label="Choose Color Palette")
            title = gr.Textbox(label="Page Title", value="My Website")
            subtitle = gr.Textbox(label="Subtitle", value="Welcome to my website")
            ai_prompt = gr.Textbox(label="Optional AI Content Prompt", placeholder="Enter prompt for AI content...")

            # Use gr.HTML to render visual preview
            preview_output = gr.HTML(label="Live Preview")
            generate_btn = gr.Button("Generate & Preview")

            # Connect function
            generate_btn.click(generate_html_with_css,
                               inputs=[template_choice, palette_name, title, subtitle, ai_prompt],
                               outputs=preview_output)
