# -*- coding: utf-8 -*-
"""html_quick_styler.ipynb00054511.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X5qY-lL4K0cyFtCo0IwW1uaiqh9Yohb1
"""

!pip install gradio transformers accelerate torch

from huggingface_hub import login

login("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")

from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model_name = "ibm-granite/granite-3.3-2b-instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16,
    device_map="auto"
)

print("Model Loaded Successfully")

def generate_html(title, description, color_style):

    prompt = f"""
    Create a responsive HTML webpage.

    Title: {title}
    Description: {description}
    Color style: {color_style}

    Include:
    - Hero section
    - Features
    - About
    - Contact form
    - Footer
    """

    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    outputs = model.generate(
        **inputs,
        max_new_tokens=400
    )

    result = tokenizer.decode(outputs[0], skip_special_tokens=True)

    return result

import gradio as gr

interface = gr.Interface(
    fn=generate_html,
    inputs=[
        gr.Textbox(label="Page Title"),
        gr.Textbox(label="Page Description"),
        gr.Dropdown(
            ["modern","vibrant","ocean","forest","sunset","luxury","creative","minimal"],
            label="Color Style"
        )
    ],
    outputs=gr.Textbox(label="Generated HTML Code"),
    title="HTML Quick Styler"
)

interface.launch(share=True)