# -*- coding: utf-8 -*-
"""HTML_Quick_Styler_Project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12FniOxy47-nUVvEefZbxAXj0WusPd4H9
"""

!pip install gradio
!pip install transformers
!pip install accelerate

from transformers import pipeline

generator = pipeline(
    "text-generation",
    model="ibm-granite/granite-3.3-2b-instruct",
    max_new_tokens=300
)

print("Model Loaded Successfully")

# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("text-generation", model="ibm-granite/granite-3.3-2b-instruct")
messages = [
    {"role": "user", "content": "Who are you?"},
]
pipe(messages)

# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
model = AutoModelForCausalLM.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
messages = [
    {"role": "user", "content": "Who are you?"},
]
inputs = tokenizer.apply_chat_template(
	messages,
	add_generation_prompt=True,
	tokenize=True,
	return_dict=True,
	return_tensors="pt",
).to(model.device)

outputs = model.generate(**inputs, max_new_tokens=40)
print(tokenizer.decode(outputs[0][inputs["input_ids"].shape[-1]:]))

from huggingface_hub import login
login()

from transformers import pipeline

generator = pipeline(
    "text-generation",
    model="ibm-granite/granite-3.3-2b-instruct",
    max_new_tokens=300
)

print("Model Loaded Successfully")

result = generator("Create a simple HTML webpage", max_new_tokens=200)
print(result[0]["generated_text"])

def generate_html(description):

    prompt = f"""
Create a responsive HTML webpage with CSS styling.

Description:
{description}

Include hero section, portfolio grid, about section,
testimonials, contact form, and footer.
"""

    result = generator(prompt)
    return result[0]["generated_text"]

import gradio as gr

interface = gr.Interface(
    fn=generate_html,
    inputs="text",
    outputs="text",
    title="HTML Quick Styler",
    description="AI Tool to Generate HTML Websites"
)

interface.launch()

generator = pipeline(
    "text-generation",
    model="ibm-granite/granite-3.3-2b-instruct",
    max_new_tokens=800
)

def generate_html(description):

    prompt = f"""
Create a complete responsive HTML webpage with internal CSS.

Description:
{description}

Include these sections:
1. Hero section
2. Portfolio grid
3. About section
4. Testimonials
5. Contact form
6. Footer

Return the full HTML code starting with <!DOCTYPE html>.
"""

    result = generator(prompt, max_new_tokens=800)

    return result[0]["generated_text"]

import gradio as gr

interface = gr.Interface(
    fn=generate_html,
    inputs="text",
    outputs="text",
    title="HTML Quick Styler"
)

interface.launch()